package be.switchfully.uno_shark.security;

public enum Feature {
    CREATE_DIVISION,
    GET_ALL_DIVISIONS,
    GET_DIVISION,
    CREATE_SUBDIVISION,
    CREATE_PARKINGLOT,
    GET_ALL_PARKINGLOTS,
    GET_PARKINGLOT,
    GET_ALL_MEMBERS,
    GET_MEMBER,
    GET_ALL_PARKINGALLOCATIONS,
    GET_ALL_PARKINGALLOCATIONS_FOR_MEMBER,
    GET_ALL_PARKINGALLOCATIONS_FOR_PARKINGLOT,
    GET_ALL_PARKINGALLOCATIONS_DURATION,
    GET_ALL_INVOICES,
    CLOSE_INVOICE,
    SELECT_MEMBERSHIP_LEVEL,
    START_ALLOCATION_PARKINGSPOT,
    STOP_ALLOCATION_PARKINGSPOT,
    GET_MONTHLY_INVOICE
}
